root: true

env:
  node: true
  es6: true

parserOptions:
  ecmaVersion: 6
  sourceType: "module"

rules:
  accessor-pairs: 2
  array-bracket-spacing: [2, "never"]
  array-callback-return: 2
  arrow-body-style: [2, "always"]
  arrow-parens: [2, "always"]
  arrow-spacing: 2
  block-scoped-var: 2
  block-spacing: [2, "always"]
  brace-style: [2, "1tbs", { "allowSingleLine": true }]
  callback-return: 2
  camelcase: [2, { "properties": "never" }]
  comma-dangle: [2, "never"]
  comma-spacing: [2, { "before": false, "after": true }]
  comma-style: [2, "last"]
  complexity: [2, 3]
  computed-property-spacing: [2, "never"]
  consistent-return: 2
  consistent-this: 2
  constructor-super: 2
  curly: [2, "all"]
  default-case: 2
  dot-location: [2, "property"]
  dot-notation: [2, { "allowKeywords": true }]
  eol-last: 2
  eqeqeq: 2
  func-names: 2
  func-style: [2, "declaration", { "allowArrowFunctions": true }]
  generator-star-spacing: [2, { "before": true, "after": false }]
  global-require: 2
  guard-for-in: 2
  handle-callback-err: [2, "^.*(e|E)rr" ]
  id-blacklist: [2, "err", "e", "cb"]
  id-length: [2, { "min": 2, "properties": "never" }]
  id-match: 0
  indent: [2, 2, { "SwitchCase": 1 }]
  init-declarations: [2, "never", { "ignoreForLoopInit": true }]
  jsx-quotes: 0
  key-spacing: [2, { "beforeColon": false, "afterColon": true }]
  keyword-spacing: 2
  linebreak-style: [2, "unix"]
  lines-around-comment: 2
  max-depth: [2, 2]
  max-len: 0
  max-nested-callbacks: [2, 3]
  max-params: [2, 3]
  max-statements: 0
  new-cap: 2
  new-parens: 2
  newline-after-var: [2, "always"]
  newline-per-chained-call: [2, { "ignoreChainWithDepth": 4 }]
  no-alert: 2
  no-array-constructor: 2
  no-bitwise: 2
  no-caller: 2
  no-case-declarations: 2
  no-catch-shadow: 2
  no-class-assign: 2
  no-cond-assign: [2, "always"]
  no-confusing-arrow: 2
  no-console: 2
  no-const-assign: 2
  no-constant-condition: 2
  no-continue: 2
  no-control-regex: 2
  no-debugger: 2
  no-delete-var: 2
  no-div-regex: 2
  no-dupe-args: 2
  no-dupe-class-members: 2
  no-dupe-keys: 2
  no-duplicate-case: 2
  no-else-return: 2
  no-empty-character-class: 2
  no-empty-function: [2, {"allow": []}]
  no-empty-pattern: 2
  no-empty: 2
  no-eq-null: 2
  no-eval: 2
  no-ex-assign: 2
  no-extend-native: 2
  no-extra-bind: 2
  no-extra-boolean-cast: 2
  no-extra-label: 2
  no-extra-parens: [2, "all"]
  no-extra-semi: 2
  no-fallthrough: 2
  no-floating-decimal: 2
  no-func-assign: 2
  no-implicit-coercion: 2
  no-implicit-globals: 2
  no-implied-eval: 2
  no-inline-comments: 2
  no-inner-declarations: [2, "both"]
  no-invalid-regexp: 2
  no-invalid-this: 2
  no-irregular-whitespace: 2
  no-iterator: 2
  no-label-var: 2
  no-labels: 2
  no-lone-blocks: 2
  no-lonely-if: 2
  no-loop-func: 2
  no-magic-numbers: [2, { ignore: [0, 1] }]
  no-mixed-requires: [2, { "grouping": true }]
  no-mixed-spaces-and-tabs: 2
  no-multi-spaces: 2
  no-multi-str: 2
  no-multiple-empty-lines: [2, {max: 1}]
  no-native-reassign: 2
  no-negated-condition: 2
  no-negated-in-lhs: 2
  no-nested-ternary: 2
  no-new-func: 2
  no-new-object: 2
  no-new-require: 2
  no-new-symbol: 2
  no-new-wrappers: 2
  no-new: 2
  no-obj-calls: 2
  no-octal-escape: 2
  no-octal: 2
  no-param-reassign: [2, { "props": false }]
  no-path-concat: 2
  no-plusplus: [2, { allowForLoopAfterthoughts: true }]
  no-process-env: 0
  no-process-exit: 2
  no-proto: 2
  no-redeclare: 2
  no-regex-spaces: 2
  no-restricted-imports: 0
  no-restricted-modules: 0
  no-restricted-syntax: 0
  no-return-assign: 2
  no-script-url: 2
  no-self-assign: 2
  no-self-compare: 2
  no-sequences: 2
  no-shadow-restricted-names: 2
  no-shadow: 2
  no-spaced-func: 2
  no-sparse-arrays: 2
  no-sync: 2
  no-ternary: 0
  no-this-before-super: 2
  no-throw-literal: 2
  no-trailing-spaces: 2
  no-undef-init: 2
  no-undef: 2
  no-undefined: 2
  no-underscore-dangle: 2
  no-unexpected-multiline: 2
  no-unmodified-loop-condition: 2
  no-unneeded-ternary: 2
  no-unreachable: 2
  no-unused-expressions: 2
  no-unused-labels: 2
  no-unused-vars: 2
  no-use-before-define: [2, { "functions": false, "classes": true }]
  no-useless-call: 2
  no-useless-concat: 2
  no-useless-constructor: 2
  no-var: 2
  no-void: 2
  no-warning-comments: [2, { "location": "anywhere" }]
  no-whitespace-before-property: 2
  no-with: 2
  object-curly-spacing: [2, "always"]
  object-shorthand: 2
  one-var-declaration-per-line: [2, "always"]
  one-var: [2, "never"]
  operator-assignment: [2, "always"]
  operator-linebreak: [2, "after", { "overrides": { "?": "before", ":": "before"} }]
  padded-blocks: [2, "never"]
  prefer-arrow-callback: 2
  prefer-const: 2
  prefer-reflect: 2
  prefer-rest-params: 2
  prefer-spread: 2
  prefer-template: 2
  quote-props: [2, "as-needed"]
  quotes: [2, "backtick", "avoid-escape"]
  radix: [2, "always"]
  require-jsdoc: 0
  require-yield: 2
  semi-spacing: 2
  semi: [2, "always"]
  sort-imports: 2
  sort-vars: 2
  space-before-blocks: 2
  space-before-function-paren: [2, { "anonymous": "always", "named": "never" }]
  space-in-parens: [2, "never"]
  space-infix-ops: 2
  space-unary-ops: 2
  spaced-comment: [2, "always"]
  strict: 2
  template-curly-spacing: [2, "always"]
  use-isnan: 2
  valid-jsdoc: 2
  valid-typeof: 2
  vars-on-top: 2
  wrap-iife: [2, "inside"]
  wrap-regex: 2
  yield-star-spacing: [2, { "before": true, "after": false }]
  yoda: 2
